--- 
max_conns: 1024
pid: tmp/pids/thin.pid
chdir: /var/www/robotics.stratosphe.re/
servers: 3
port: 3000
daemonize: true
timeout: 30
wait: 30
log: log/thin.log
require: []

max_persistent_conns: 100
environment: production
address: 0.0.0.0
